KoboldAI/KoboldAI-Client

- aiserver.py
I found two issues that can cause the import to fail. This pull request fixes them.
1. Some older versions of the downloader script put the export in one big file. This checks for that so the import still succeeds.
2. If you never used Author's Note (because you didn't have a subscription), it will be `None`. This caused a `TypeError` when you try to continue the story.
> Import fixes

- aiserver.py
Huge performance increase when generating the HTML by putting all the text chunks in a list before assembling. Speeds up generation by orders of magnitude on large stories. (In my test case, a 2000+ action story went from taking 500ms to generating so fast the monotonic clock didn't have enough resolution to measure it)
The original problem has caused by the fact that when adding strings using `+` and `+=`, memory is allocated to fit both strings being concatenated and then the two are copied in this new area in memory. This meant that for every action added *all the HTML generated to up this point has to be copied* in a new spot in memory. *Every. Time.*
As lists are more flexible mutable containers, there's a lot less memory allocation, and the components can easily and efficiently be …
> Performance increase for `refresh_story` on large stories

- aiserver.py
As 1e95f7e1a5efa906d79430ada57f387976c1a797 doesn't escape the user prompt, this will be changed with this, it will also be escaped.
closes #22
> Escape user prompt

- install_requirements.bat
I changed the menu order around because Finetuneanon's version is better for most users and needed for 6B.
The github branch it downloads for finetune is updated, and it can now fix the download path length errors if ran as admin.
> 6B update & stability fixes

- install_requirements.bat
No more manually forcing CUDA to be 11, instead we use conda-forge.
This will pull down a lot more recent versions of pretty much everything, and fixes errors in the GPT-J models that cropped up on the older versions of the dependencies.
> Migrated install_requirements.bat to conda-forge

- docker-cuda/Dockerfile
- docker-cuda/docker-compose.yml
- docker-rocm/Dockerfile
- docker-rocm/docker-compose.yml
- environments/finetuneanon.yml
- environments/huggingface.yml
- install_requirements.bat
- play-cuda.sh
- play-rocm.sh
- play.bat
Big overhaul of the installer, partially based on the #53  commit from LexSong.
The following is new :
- Conda has been replaced with MicroMamba, allows the dependencies to automatically download the best version of Python and prevents all the issues with people failing to download conda.
- The installer now has more options so you can choose not to delete the existing files, and it has new optional virtual K: drive support to bypass all the pathing issues people are having (Sorry Windows 7 users, its still not compatible even now).
- Docker support for Linux systems has been added including ROCm support.
- Environment files are now used to more easily keep everything on track, and to allow conda users to manually create environments across all operating systems (ROCm is an outlier in …
> The Mamba Installer Update

- .gitignore
- aiserver.py
- static/application.js
Rather than updating the whole story in the UI, these codes changes make it so that only affected HTML chunk elements are changed. This makes working with large stories much smoother (it's actually surprising just how smoothly it works considering that rather minimal code changes!).
It does this by introducing two new server messages:
Updates a story chunk. The data is an object with the following keys:
* `index`: The index of the chunk (not the action! with `0` being the prompt).
* `html`: The HTML markup of the new replacement chunk.
* `last`: Is this the chunk for the last action of the story (used to determine if the UI should scroll down).
The frontend code creates a new HTML element and puts it in place of the existing one according to the chunk index. If there is no existing HTML …
> Update or remove targeted chunks in Game Screen rather than refreshing everything

- aiserver.py
This fixes breakmodel mode for the official models from the model selection menu.
> Change AutoModel to AutoModelForCausalLM

- static/application.js
- templates/index.html
The behaviour varied between browsers but it was universally undesirable in some way outside of Firefox on desktop/Android.
This patch is tested in Chrome and Firefox in Windows 10 and Android 11, Firefox in Ubuntu 16.04, and Safari in macOS Big Sur and iOS 14 (iPhone and iPad).
On a side note it seems like the newest desktop Firefox version somehow broke the ability to delete text from multiple chunks at once by selecting multiple chunks and then pressing backspace. I'll look into that.
> Fix enter key behaviour in the editor when not using Firefox

- aiserver.py
This prevents the "thinking" animation from appearing on top of the
submit button under certain circumstances:
* When someone connects to the KoboldAI server while the model is generating (occurs after generation finishes)
* Occasionally, the browser may suddenly disconnect and reconnect from Flask-SocketIO during generation, which causes the same problem
> Don't broadcast emit calls inside do_connect()

- aiserver.py
The models from Hugging Face's model hub usually have a forward slash in their name, which we would not like in the name for settings files.
> Replace slashes in model name with underscores

- static/application.js
- templates/index.html
When Firefox 93.0 was released, they broke the ability to edit text across multiple chunks or across multiple paragraphs. If you tried, nothing would happen.
Also, we are no longer using Mutation Observers to detect when a chunk is modified. We are now using the beforeinput event.
> Fix some editor issues in Firefox and possibly mobile browsers

- aiserver.py
Fixing a spacing issue in chat mode. Makes names go from "John :" to "John:", like they're supposed to be.
> Fix glaring issue in chat mode

- aiserver.py
They released another version of transformers that still doesn't have the OPT patch so I decided it would be safer to just mark all 4.19 transformers versions as needing the OPT patch.
> Update list of versions with broken OPT again

- aiserver.py
- tpu_mtj_backend.py
The OPT tokenizer in transformers was recently updated so that the output of `tokenizer.encode` now has the `</s>` token put at the beginning of the output. This causes a lot of problems with KoboldAI because a separate `tokenizer.encode` call is used to encode every chunk of the story so it's putting a lot of extra `</s>` tokens into the story.
This pull request fixes the OPT tokenizer so that it only puts a single `</s>` token at the beginning of the story which is the intended behavior of tokenization for the OPT models.
Also fixes a problem where the OPT-350M model outputs gibberish in transformers 4.20.0 when running the model locally after it's been saved by KoboldAI.
> Fix OPT tokenization problems

- aiserver.py
This makes the GPT-NeoX HF model actually use the correct badwords list.
When merging to united, just remove all the changes.
> GPT-NeoX HF model badwords fix

- static/application.js
* Fixes the issue where inserting a newline at the end of the last action in the story sometimes inserts two newlines instead
* Fixes the issue where editing the story and then directly clicking on the Submit button without defocusing the story first results in the story changes not being submitted
* The prompt can now be edited properly again, and without any JavaScript errors
> Editor fixes

- torch_lazy_loader.py
There is no `torch._StorageBase` in PyTorch 1.12, but otherwise it still works.
> Fix for lazy loader in PyTorch 1.12

- utils.py
transformers 4.21.0 changed the error that gets thrown when a model isn't found in the cache.
> Fix aria2 in Colab

- aiserver.py
This fixes an issue on non-Windows operating systems where when KoboldAI tries to move the model files out of the HF cache, it moves a symlink to the pytorch_model.bin.index.json out of the cache instead of the real pytorch_model.bin.index.json file, so when the cache is deleted, the symlink would be broken.
> Fix saving of sharded HF models on non-Windows operating systems

- aiserver.py
- tpu_mtj_backend.py
This fixes an issue where loading a GPT-NeoX model results in warnings being printed to the console and the GPT-2 tokenizer being used instead.
> Fix tokenizer selection code

- aiserver.py
This fixes the "is on the meta device" error when you try to load a GPT-Neo, GPT-J or GPT-NeoX model with at least one layer in disk cache. Also, I have disabled the converting of the saved model from 32-bit to 16-bit when disk cache is used because save_pretrained isn't compatible with accelerate's disk cache.
> Fix "is on the meta device" error when loading model with disk cache

- maps/gptj.json
- tpu_mtj_backend.py
This fixes the error you get when you load the https://huggingface.co/rexwang8/qilin-lit-6b model in the TPU Colab. Normally, when the number of tokens in the model's token vocabulary is not divisible by 8 in a TPU Colab, we have to pad the token vocabulary with dummy tokens to make it divisible by 8. This was being done improperly for GPT-J models in particular.
> Fix GPT-J model loading in TPU Colab when `vocab_size` is not divisible by 8

- tpu_mtj_backend.py
This fixes compatibility with the original mesh-transformer-jax GPT-J format that you load with TPUMeshTransformerGPTJ.
> Only enable TPU transpose optimization if loading from HF model

- requirements_mtj.txt
Since MTJ is low level, we force a fixed transformers version to have more controlled updates when needed. This fixes today's loading errors.
> Cap transformers version

- environments/huggingface.yml
- environments/rocm.yml
- requirements.txt
- requirements_mtj.txt
To avoid breaking changes lets force the exact transformers version we code against. This will be automatically picked up by all the automatic updaters.
> Pin transformers version

- docker-cuda/docker-compose.yml
- docker-rocm/docker-compose.yml
With selinux enabled distros containers accessing KoboldAIs main directory as content, as planned here, will likely generally be denied (atleast with podman). Option 1 would be to mark it with the right label - like :z - but that has other Implications for the content directory.
The other fix, if uglier, is to run the container without labels being enforced and thus allow the file access as the same user and with no further sideeffects to the project file labelling.
> Allow Project File Access with Podman+Selinux
